"""Agent consumption of BMD Compute v1 contracts.

BMD Compute is authoritative for every contract exercised here. The fixtures in
``fixtures/compute_v1`` are generated by Compute's own producers (see
``fixtures/compute_v1/SOURCE.md``); Agent reads them, it does not recompute them.
"""

from __future__ import annotations

from copy import deepcopy
from dataclasses import replace
import hashlib
import json
from pathlib import Path
import subprocess

import pytest

from bmd_agent import cli
from bmd_agent.presentation import build_job_concise_summary, render_concise_summary
from bmd_agent.resources.compute import (
    ComputeCapabilityError,
    parse_capability_payload,
    supported_capability_pairs,
    supported_modifier_combinations,
)
from bmd_agent.resources.compute_records import (
    AUTOMATIC_TREATMENTS_NONE,
    AUTOMATIC_TREATMENTS_NOT_RECORDED,
    AUTOMATIC_TREATMENTS_RECORDED,
    AUTOMATIC_TREATMENTS_UNAVAILABLE,
    INVALID_RECORD,
    PROVENANCE_LEGACY,
    PROVENANCE_UNSUPPORTED,
    PROVENANCE_V1,
    RUNTIME_RECORD_INVALID,
    RUNTIME_RECORD_NOT_RECORDED,
    RUNTIME_RECORD_RECORDED,
    RUNTIME_RECORD_UNAVAILABLE,
    RUNTIME_RECORD_UNSUPPORTED,
    UNSUPPORTED_VERSION,
    ComputeRecordError,
    observe_runtime_environment,
    parse_runtime_environment_record,
    parse_submission_record,
    read_automatic_treatments,
)
from bmd_agent.resources.custodian import custodian_policy_from_submission_record
from bmd_agent.resources.input_reference import parse_input_reference_payload
from bmd_agent.resources.lifecycle import analyze_calculation_directory
from bmd_agent.resources.run import inspect_remote_run

import test_compute
import test_run_inspection as ri


FIXTURES = Path(__file__).parent / "fixtures" / "compute_v1"
RUN_RECORD_FIXTURES = Path(__file__).parent / "fixtures" / "compute_run_records" / "v1"
CHECK_INPUT_FIXTURE = Path(__file__).parent / "fixtures" / "check_input" / "compute_generated_cases.json"
COMPUTE_V1_COMMIT = "a746155b487f903a167eca6b3c92e860aaf8c7f5"


def load(name: str):
    return json.loads((FIXTURES / name).read_text(encoding="utf-8"))


def capabilities_payload() -> dict:
    return load("capabilities.json")


def desired_output_submission() -> dict:
    return load("desired_output_nio/submission.json")


def custom_submission() -> dict:
    return load("custom_workflow_nio/submission.json")


def passed_record() -> dict:
    return load("runtime_environment_passed.json")


def failed_record() -> dict:
    return load("runtime_environment_failed.json")


def assert_kind(payload, kind):
    with pytest.raises(ComputeRecordError) as exc_info:
        parse_runtime_environment_record(payload)
    assert exc_info.value.kind == kind
    return exc_info.value


def test_fixtures_match_their_checksum_manifest():
    listed = {}
    for line in (FIXTURES / "SHA256SUMS").read_text(encoding="utf-8").splitlines():
        digest, name = line.split("  ", 1)
        listed[name] = digest
    present = {
        path.relative_to(FIXTURES).as_posix()
        for path in FIXTURES.rglob("*.json")
    }
    assert set(listed) == present
    for name, digest in listed.items():
        assert hashlib.sha256((FIXTURES / name).read_bytes()).hexdigest() == digest


# --- capability contract ------------------------------------------------------------------


def test_current_compute_capability_payload_parses_with_all_eight_capabilities():
    capabilities = parse_capability_payload(json.dumps(capabilities_payload()))

    assert capabilities.source["commit"] == COMPUTE_V1_COMMIT
    assert capabilities.source["dirty"] is False
    pairs = set(supported_capability_pairs(capabilities))
    assert len(pairs) == 8
    assert ("dos", "hse06") in pairs
    assert pairs == {
        (stage, theory)
        for stage in ("relax", "static", "dos", "band_structure")
        for theory in ("pbe", "hse06")
    }


def test_stage_modifier_support_is_preserved_verbatim():
    payload = capabilities_payload()
    capabilities = parse_capability_payload(json.dumps(payload))

    assert capabilities.stage_modifier_support == tuple(payload["stage_modifier_support"])
    for record in payload["stage_modifier_support"]:
        declared = supported_modifier_combinations(
            capabilities,
            record["stage_type"],
            record["theory"],
        )
        assert declared == tuple(
            frozenset(combination) for combination in record["supported_modifier_combinations"]
        )


def test_representative_allowed_and_forbidden_stage_modifiers_come_from_compute():
    capabilities = parse_capability_payload(json.dumps(capabilities_payload()))

    pbe_dos = supported_modifier_combinations(capabilities, "dos", "pbe")
    pbe_static = supported_modifier_combinations(capabilities, "static", "pbe")
    hse_static = supported_modifier_combinations(capabilities, "static", "hse06")
    pbe_relax = supported_modifier_combinations(capabilities, "relax", "pbe")

    assert frozenset({"dft_u", "spin_polarized"}) in pbe_dos
    assert all("soc" not in combination for combination in pbe_dos)
    assert frozenset({"soc"}) in pbe_static
    assert frozenset({"soc"}) in hse_static
    assert frozenset({"dispersion"}) not in hse_static
    assert all("soc" not in combination for combination in pbe_relax)


def test_historical_capability_payload_without_modifier_support_still_parses():
    capabilities = parse_capability_payload(json.dumps(test_compute.schema_v1_payload()))

    assert capabilities.stage_modifier_support is None
    # Not declared means unknown, never "no modifiers".
    assert supported_modifier_combinations(capabilities, "static", "pbe") is None


def test_modifier_support_is_not_inferred_from_broad_treatment_descriptions():
    payload = capabilities_payload()
    soc_policy = next(
        item
        for item in payload["automatic_default_treatments"]["treatments"]
        if item["modifier"] == "soc"
    )
    # The policy prose says SOC applies to "every non-relaxation stage" ...
    assert "non-relaxation" in soc_policy["application"]
    capabilities = parse_capability_payload(json.dumps(payload))
    # ... but only stage_modifier_support decides; Compute rejects SOC on PBE DOS.
    assert all("soc" not in combination for combination in supported_modifier_combinations(capabilities, "dos", "pbe"))

    historical = deepcopy(payload)
    historical.pop("stage_modifier_support")
    historical_capabilities = parse_capability_payload(json.dumps(historical))
    # With no declared support, Agent reports nothing rather than reading the policy text.
    assert supported_modifier_combinations(historical_capabilities, "dos", "pbe") is None


@pytest.mark.parametrize(
    "mutate",
    [
        lambda p: p["stage_modifier_support"].append(dict(p["stage_modifier_support"][0])),
        lambda p: p["stage_modifier_support"][0].update(supported_modifier_combinations="soc"),
        lambda p: p["stage_modifier_support"][0].update(stage_type="phonons"),
    ],
)
def test_malformed_stage_modifier_support_is_rejected(mutate):
    payload = capabilities_payload()
    mutate(payload)

    with pytest.raises(ComputeCapabilityError, match="stage_modifier_support"):
        parse_capability_payload(json.dumps(payload))


def test_compute_command_displays_declared_modifier_sets(capsys):
    cli.print_compute_capabilities(parse_capability_payload(json.dumps(capabilities_payload())))
    output = capsys.readouterr().out

    flat = " ".join(output.split())
    assert "HSE06 DOS" in flat
    assert (
        "accepted modifier sets: no modifiers, dft_u, gamma_only, spin_polarized, "
        "dft_u+gamma_only, dft_u+spin_polarized, gamma_only+spin_polarized, "
        "dft_u+gamma_only+spin_polarized"
    ) in flat
    assert "not declared by this BMD Compute producer" not in output


def test_compute_command_states_when_modifier_support_is_not_declared(capsys):
    cli.print_compute_capabilities(parse_capability_payload(json.dumps(test_compute.schema_v1_payload())))
    output = capsys.readouterr().out

    assert "accepted modifier sets" not in output
    assert "not declared by this BMD Compute producer" in output


# --- runtime_environment v1 ---------------------------------------------------------------


def test_passed_runtime_record_is_parsed():
    record = parse_runtime_environment_record(passed_record())

    assert record.status == "passed" and record.passed
    assert record.problems == ()
    assert record.label == "bmd_compute.runtime_environment v1"
    assert record.prepared_packages == record.runtime_packages
    assert record.runtime_packages["pymatgen-core"] == "2026.7.16"
    assert record.supporting_packages["numpy"] == "2.5.1"
    assert record.atomate2_settings["VASP_INCAR_UPDATES"] == {}
    assert record.parity_policy["policy_id"] == "bmd_compute.runtime_parity"
    assert record.attempt_id == "00000000-0000-4000-8000-000000000201"
    assert record.slurm_job_id == "10000201"


def test_failed_runtime_record_is_parsed_with_compute_problems():
    record = parse_runtime_environment_record(failed_record())

    assert record.status == "failed" and not record.passed
    assert record.problems == (
        "pymatgen-core: prepared 2026.7.16, runtime 2026.6.1.",
        "atomate2 VASP_INCAR_UPDATES is set ({'ENCUT': 600}); it would change BMD's INCARs at write time.",
    )
    assert record.prepared_packages["pymatgen-core"] == "2026.7.16"
    assert record.runtime_packages["pymatgen-core"] == "2026.6.1"


def test_failed_status_is_never_read_as_a_pass_even_when_versions_agree():
    payload = failed_record()
    payload["runtime_packages"] = dict(payload["prepared_packages"])
    payload["problems"] = ["atomate2 VASP_INHERIT_INCAR is enabled (True)."]

    record = parse_runtime_environment_record(payload)

    # Agent reports Compute's verdict; it does not recompute parity from versions.
    assert record.status == "failed"
    assert record.prepared_packages == record.runtime_packages


def test_unknown_additive_runtime_fields_are_preserved():
    payload = passed_record()
    payload["gpu_runtime"] = {"cuda": None}

    record = parse_runtime_environment_record(payload)

    assert record.additional_fields == {"gpu_runtime": {"cuda": None}}


@pytest.mark.parametrize("version", [2, 0])
def test_unknown_major_runtime_schema_is_rejected_as_unsupported(version):
    payload = passed_record()
    payload["schema_version"] = version

    error = assert_kind(payload, UNSUPPORTED_VERSION)
    assert f"schema_version {version}" in str(error)


@pytest.mark.parametrize(
    "mutate",
    [
        lambda p: p.pop("schema"),
        lambda p: p.update(schema="bmd_compute.submission"),
        lambda p: p.update(schema_version="1"),
        lambda p: p.update(status="ok"),
        lambda p: p.update(problems="none"),
        lambda p: p.update(problems=["stale package"]),  # passed + problems
        lambda p: p.update(runtime_packages=["atomate2"]),
        lambda p: p.update(runtime_packages={"atomate2": 1}),
    ],
)
def test_malformed_runtime_record_is_invalid(mutate):
    payload = passed_record()
    mutate(payload)

    assert_kind(payload, INVALID_RECORD)


def test_runtime_observation_reports_unsupported_and_invalid_without_a_verdict():
    future = passed_record()
    future["schema_version"] = 2

    unsupported = observe_runtime_environment(future, path="/run/runtime_environment.json")
    invalid = observe_runtime_environment({"status": "passed"}, path="/run/runtime_environment.json")

    assert unsupported.status == RUNTIME_RECORD_UNSUPPORTED and unsupported.parity_status is None
    assert invalid.status == RUNTIME_RECORD_INVALID and invalid.parity_status is None


def test_runtime_record_attempt_mismatch_is_a_limitation_not_a_verdict_change():
    submission = parse_submission_record(custom_submission())  # attempt ...0202

    observation = observe_runtime_environment(passed_record(), path="/x", submission=submission)

    assert observation.status == RUNTIME_RECORD_RECORDED
    assert observation.parity_status == "passed"
    assert any("attempt_id" in item for item in observation.limitations)


# --- runtime record in run inspection -----------------------------------------------------


def no_scheduler(command, **kwargs):
    return subprocess.CompletedProcess(command, 0, stdout="", stderr="")


def inspect_v1_run(runtime_payload: bytes | None):
    submission = desired_output_submission()
    run_dir = submission["paths"]["run_dir"]
    files = {f"{run_dir}/submission.json": json.dumps(submission).encode("utf-8")}
    if runtime_payload is not None:
        files[submission["paths"]["runtime_environment"]] = runtime_payload
    remote = ri.RemoteFixture(files=files, directories={run_dir})
    return inspect_remote_run(
        ri.cluster(),
        run_dir,
        remote_runner=remote,
        slurm_runner=no_scheduler,
        derive_scientific=False,
    )


def test_remote_v1_run_reads_failed_runtime_record(capsys):
    inspection = inspect_v1_run((FIXTURES / "runtime_environment_failed.json").read_bytes())

    assert inspection.runtime_environment.status == RUNTIME_RECORD_RECORDED
    assert inspection.runtime_environment.parity_status == "failed"
    cli.print_run_inspection(inspection)
    output = capsys.readouterr().out
    assert "Runtime parity: FAILED" in output
    assert "problem: pymatgen-core: prepared 2026.7.16, runtime 2026.6.1." in output
    assert "pymatgen-core: 2026.7.16 -> 2026.6.1" in output
    assert "VASP_INCAR_UPDATES: {'ENCUT': 600}" in output
    assert "BMD Compute stopped this run before building the workflow or starting VASP." in output


def test_remote_v1_run_reads_passed_runtime_record(capsys):
    inspection = inspect_v1_run((FIXTURES / "runtime_environment_passed.json").read_bytes())

    assert inspection.runtime_environment.parity_status == "passed"
    cli.print_run_inspection(inspection)
    output = capsys.readouterr().out
    assert "Runtime parity: PASSED" in output
    assert "supporting packages (recorded, not parity-checked):" in output
    assert "problem:" not in output


def test_declared_but_missing_runtime_record_is_unavailable_not_passed(capsys):
    inspection = inspect_v1_run(None)

    assert inspection.runtime_environment.status == RUNTIME_RECORD_UNAVAILABLE
    assert inspection.runtime_environment.parity_status is None
    cli.print_run_inspection(inspection)
    output = capsys.readouterr().out
    assert "Runtime parity: unavailable" in output
    assert "PASSED" not in output


def test_historical_run_without_runtime_record_keeps_log_fallback(capsys):
    remote = ri.RemoteFixture(files=ri.default_files(), directories=ri.default_directories())

    inspection = inspect_remote_run(
        ri.cluster(),
        ri.FLOW_ROOT,
        remote_runner=remote,
        slurm_runner=ri.slurm_runner,
        scientific_parser=ri.fake_scientific_parser,
        modifier_policies=(ri.modifier_policy(),),
    )

    assert inspection.runtime_environment.status == RUNTIME_RECORD_NOT_RECORDED
    # The pre-existing runner-log evidence is still collected unchanged.
    assert inspection.runtime.packages["pymatgen"] == "2026.8.13"
    assert not any("runtime_environment.json" in " ".join(command) for command in remote.commands)
    cli.print_run_inspection(inspection)
    output = capsys.readouterr().out
    assert "Runtime parity: not recorded" in output
    assert "runner-log lines under Logs are this run's only runtime evidence" in output
    assert "pymatgen: 2026.8.13" in output


@pytest.mark.parametrize("case", ("single_stage_pbe_static", "hse06_soc_after_pbe_relax"))
def test_vendored_historical_v1_records_declare_no_runtime_record(case):
    submission = json.loads((RUN_RECORD_FIXTURES / case / "submission.json").read_text(encoding="utf-8"))

    record = parse_submission_record(submission)

    assert record.runtime_environment_path is None
    assert record.runtime_parity is None


def test_concise_job_summary_reports_compute_runtime_failure():
    from test_presentation import bmd_job, scheduler

    runtime = inspect_v1_run((FIXTURES / "runtime_environment_failed.json").read_bytes()).runtime_environment
    job = bmd_job(scheduler_record=scheduler(state="FAILED", exit_code="1:0"))
    job = replace(
        job,
        bmd_compute=replace(
            job.bmd_compute,
            inspection=replace(job.bmd_compute.inspection, runtime_environment=runtime),
        ),
    )

    output = " ".join(render_concise_summary(build_job_concise_summary(job)).split())

    assert "BMD Compute stopped the run before VASP started: its runtime environment check failed." in output
    assert "BMD Compute reported: pymatgen-core: prepared 2026.7.16, runtime 2026.6.1." in output


def test_local_snapshot_reads_declared_runtime_record(tmp_path, capsys):
    submission = desired_output_submission()
    producer_root = submission["paths"]["run_dir"]
    root = tmp_path / Path(producer_root).name
    root.mkdir()
    (root / "submission.json").write_text(json.dumps(submission), encoding="utf-8")
    (root / "runtime_environment.json").write_bytes(
        (FIXTURES / "runtime_environment_failed.json").read_bytes()
    )

    analysis = analyze_calculation_directory(root)

    observation = analysis.bmd_workflow.runtime_environment
    assert observation.status == RUNTIME_RECORD_RECORDED
    assert observation.parity_status == "failed"
    cli.print_lifecycle_analysis(analysis)
    assert "Runtime parity: FAILED" in capsys.readouterr().out


# --- provenance version handling ----------------------------------------------------------


def test_v1_provenance_is_read_intentionally():
    record = parse_submission_record(desired_output_submission())

    assert record.provenance_contract == PROVENANCE_V1
    assert record.limitations == ()
    assert record.provenance["bmd_compute"]["source"]["git_commit"] == COMPUTE_V1_COMMIT
    assert custodian_policy_from_submission_record(record).available is True


def test_v1_provenance_tolerates_additive_fields():
    submission = desired_output_submission()
    submission["provenance"]["future_section"] = {"anything": 1}
    submission["provenance"]["execution"]["future_field"] = True

    record = parse_submission_record(submission)

    assert record.provenance_contract == PROVENANCE_V1
    assert read_automatic_treatments(record).status == AUTOMATIC_TREATMENTS_RECORDED


@pytest.mark.parametrize("version", [2, "1"])
def test_unsupported_provenance_version_is_not_interpreted(version):
    submission = desired_output_submission()
    submission["provenance"]["schema_version"] = version

    record = parse_submission_record(submission)

    assert record.contract == "v1"  # the submission itself is still readable
    assert record.provenance_contract == PROVENANCE_UNSUPPORTED
    assert record.provenance == {}
    assert any(f"schema_version {version!r}" in item for item in record.limitations)
    policy = custodian_policy_from_submission_record(record)
    assert policy.available is False and "not supported" in policy.reason
    assert read_automatic_treatments(record).status == AUTOMATIC_TREATMENTS_UNAVAILABLE


def test_vendored_v1_records_keep_their_existing_provenance_reading():
    submission = json.loads(
        (RUN_RECORD_FIXTURES / "single_stage_pbe_static" / "submission.json").read_text(encoding="utf-8")
    )

    record = parse_submission_record(submission)

    assert record.provenance_contract == PROVENANCE_V1
    assert record.limitations == ()
    assert custodian_policy_from_submission_record(record).available is True


def test_v1_submission_with_unversioned_provenance_is_legacy_with_limitation():
    submission = desired_output_submission()
    submission["provenance"].pop("schema_version")

    record = parse_submission_record(submission)

    assert record.provenance_contract == PROVENANCE_LEGACY
    assert record.provenance  # still read best-effort
    assert any("legacy record" in item for item in record.limitations)


# --- workflow origin and automatic treatments ---------------------------------------------


def test_desired_output_automatic_treatments_are_read_from_compute_record():
    record = parse_submission_record(desired_output_submission())

    treatments = read_automatic_treatments(record)

    assert treatments.status == AUTOMATIC_TREATMENTS_RECORDED
    assert treatments.desired_output_managed is True
    assert treatments.desired_output == "energy_only"
    assert [(item.modifier, item.stage_indices) for item in treatments.applied] == [
        ("spin_polarized", (1,)),
        ("dft_u", (1,)),
    ]
    assert treatments.dft_u["decision"] == "apply"
    assert treatments.dft_u["policy_id"] == "bmd_compute.dft_u"
    assert treatments.dft_u["parameters"]["species"]["Ni"]["U"] == 6.2


def test_dft_u_modifier_alone_is_not_reported_as_automatic_dft_u(capsys):
    submission = custom_submission()
    submission["flow_spec"]["workflow_spec"]["stages"][0]["modifiers"] = ["dft_u"]

    record = parse_submission_record(submission)
    treatments = read_automatic_treatments(record)

    assert treatments.status == AUTOMATIC_TREATMENTS_NONE
    assert treatments.applied == () and treatments.dft_u is None
    cli._print_automatic_treatments(treatments)
    output = capsys.readouterr().out
    assert "automatic DFT+U" not in output
    assert "workflow origin: BMD-managed Desired Output" not in output
    assert "workflow origin: not established" in output


def test_runs_prepared_before_automatic_treatment_records_say_not_recorded():
    submission = desired_output_submission()
    submission["provenance"]["execution"].pop("automatic_treatments")

    treatments = read_automatic_treatments(parse_submission_record(submission))

    assert treatments.status == AUTOMATIC_TREATMENTS_NOT_RECORDED


def test_verbose_run_inspection_shows_workflow_origin_and_frozen_dft_u(capsys):
    inspection = inspect_v1_run((FIXTURES / "runtime_environment_passed.json").read_bytes())

    cli.print_run_inspection(inspection)
    output = capsys.readouterr().out

    assert "workflow origin: BMD-managed Desired Output (energy_only)" in output
    assert "applied: DFT+U (stages 1)" in output
    assert "automatic DFT+U: decision apply (bmd_compute.dft_u v1)" in output
    assert "frozen parameters: Ni U=6.2 (LDAUTYPE 2)" in output


# --- input reference ----------------------------------------------------------------------


def test_current_input_reference_representation_parses():
    data = json.loads(CHECK_INPUT_FIXTURE.read_text(encoding="utf-8"))

    parsed = [parse_input_reference_payload(json.dumps(item["payload"])) for item in data["references"]]

    assert {response.status for response in parsed} == {"ok", "unsupported", "error"}
    ok = [item["payload"] for item in data["references"] if item["payload"]["status"] == "ok"]
    assert all(payload["producer"]["source"]["commit"] == COMPUTE_V1_COMMIT for payload in ok)
    assert all(payload["reference_phase"] == "generated_pre_execution" for payload in ok)
